export enum ActionType {
  DESCRIPTION_CHANGED = "DESCRIPTION_CHANGED",
  TITLE_CHANGED = "TITLE_CHANGED",
  UPDATE_LISTS = "UPDATE_LISTS",
  UPDATE_LIST_RESULT = "UPDATE_LIST_RESULT",
  OPEN_MODAL = "OPEN_MODAL",
  CLOSE_MODAL = "CLOSE_MODAL",
  DELETE_LIST = "DELETE_LIST",
  DELETE_LIST_RESULT = "DELETE_LIST_RESULT",
  EDIT_LIST = "EDIT_LIST",
}
